### ISSUE TITLE
Conference / Expo checklist

### ISSUE THREAD

**Issue by madjin** [NEON-BUIDL/booths#2]
Checklist

- [x] Name of the event
- [x] Video promo (team: chillzone / Arashi / Altered)
- [x] Poster (@jack-perlman point person)
- [x] Booths (@madjin point person)
- [ ] Worlds (Everyone)
  - [x] Day version
  - [ ] Night version
    - [ ] Open brush assets
- [ ] Website (@madjin)

  
Website should be simple: main idea + schedule + location. Aiming to kick things off March 10th and go on for a few weeks

**Comment by madjin** [comment]
Possible names:

- Metaverse Makers Faire
- Neon Street Festival
- Metaverse Makers Market
- THE Open Metaverse Expo
- Farmers Market
- Crypto NFT Blockchain Metaverse Conference Expo

**Comment by solarbeam0x** [comment]
Neón street festival ++ 

neon meta market 1 

neón block party

**Comment by gm3** [comment]
I like Metaverse Makers Market, or Metaverse Market for even shorter, M3CON, MakerCON, OpenMarket, MakerFEST, MetaFest, or can call it some thing like MAJIN: 2023   an acronym for something maybe
